alert("Welcome")
var language = prompt("Do you know english language?")
var name = prompt("What is your name?")
var sourname = prompt("What is your sourname?")
var country = prompt("What country are you from?")
var freetime = prompt("What do you like doing in your free time?") 
var live = prompt("Where do you live?")
var study = prompt("Where do you Study?")
var book = prompt("What subjects do you like?")
var colour = prompt("What is your favorite color?")
alert("Goodbye")